# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='element',
        ),
        migrations.RemoveField(
            model_name='document',
            name='template_format',
        ),
        migrations.RemoveField(
            model_name='extractedelements',
            name='document',
        ),
        migrations.RemoveField(
            model_name='extractedelements',
            name='element',
        ),
        migrations.AlterUniqueTogether(
            name='templateelement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='templateelement',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templateformat',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='ExtractedElements',
        ),
        migrations.DeleteModel(
            name='TemplateElement',
        ),
        migrations.DeleteModel(
            name='TemplateFormat',
        ),
    ]
