# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20160618_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Name of the Category')),
                ('description', models.TextField(blank=True, default='')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True, verbose_name='Name of the Category'), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='name of document')),
                ('document', models.FileField(upload_to='documents')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='document_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1_coordinate', models.FloatField()),
                ('y1_coordinate', models.FloatField()),
                ('x2_coordinate', models.FloatField()),
                ('y2_coordinate', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255, verbose_name='Name of the Element')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=225, unique=True, verbose_name='Name of template format')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=225, unique=True, verbose_name='Name of template format'), unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='Category of the Format')),
            ],
        ),
        migrations.AddField(
            model_name='templateelement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TemplateFormat', verbose_name='Base Format of the element'),
        ),
        migrations.AddField(
            model_name='extractedelements',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TemplateElement'),
        ),
        migrations.AddField(
            model_name='document',
            name='element',
            field=models.ManyToManyField(through='base.ExtractedElements', to='base.TemplateElement'),
        ),
        migrations.AddField(
            model_name='document',
            name='template_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TemplateFormat'),
        ),
        migrations.AlterUniqueTogether(
            name='templateelement',
            unique_together=set([('template', 'element_name')]),
        ),
    ]
