# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160620_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uuid',
            new_name='id',
        ),
    ]
