# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160620_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_resolution_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='image_resolution_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedelements',
            name='block_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedelements',
            name='block_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
