# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160621_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedelements',
            name='x2_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedelements',
            name='y2_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
